networks:
  doctrine.net:
    driver: bridge

services:

  toubilib.php:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprati.db
      - toubiauth.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  # service DB
  doctrine.db:
    image: 'postgres:latest'
    env_file: ./doctrine.env
    ports:
      - '5432:5432'
    networks:
      - doctrine.net
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    restart: always

  # administration de la base SQL
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - doctrine.net
    restart: unless-stopped


# d√©claration du volume persistant
volumes:
  pgdata:
