networks:
  doctrine.net:
    driver: bridge

services:
  # service DB
  doctrine.db:
    image: 'postgres:latest'
    env_file: ./doctrine.env
    ports:
      - '5432:5432'
    networks:
      - doctrine.net
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    restart: always

  # administration de la base SQL
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - doctrine.net
    restart: unless-stopped


# d√©claration du volume persistant
volumes:
  pgdata:
