networks:
  doctrine_net:
    driver: bridge

services:
  doctrine.php:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - doctrine_net
    depends_on:
      - doctrine.db
    command: sh -c "php -S 0.0.0.0:80 -t /var/php/public"

  doctrine.db:
    image: 'postgres:latest'
    env_file: ./doctrine.env
    ports:
      - '5432:5432'
    networks:
      - doctrine_net
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - doctrine_net
    restart: unless-stopped

volumes:
  pgdata:
